version: "3.8"

services:
  app:
    build: .
    # restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8001}:8000


volumes:
  db_data:
